CREATE DATABASE PERSON;
GO
CREATE TABLE PERSON(
	STT INT NOT NULL,
	FIRSTNAME NVARCHAR (50) NOT NULL,
	LASTNAME NVARCHAR(50) NOT NULL,
	NICKNAME NVARCHAR(50) NOT NULL PRIMARY KEY,
	PASSWORD NVARCHAR (50) NOT NULL,
	ROLE NVARCHAR (50) NOT NULL,
	BIRTHDAY Int NOT NULL,

)

CREATE TABLE LIST(
	nickname NVARCHAR(50) NOT NULL PRIMARY KEY,
	PASSWORD NVARCHAR (50) NOT NULL,
)

ALTER TABLE PERSON ADD CONSTRAINT FK_NICKNAME FOREIGN KEY (NICKNAME) REFERENCES LIST (nickname);

INSERT LIST
VALUES
('anvv','123'),
('binhtt','123'),
('canhlt','123'),
('duyentd','123'),
('emnn','123')
SELECT *FROM LIST;

INSERT PERSON
VALUES
('1','Nguyen Van','An','anvv','123','Manager','60'),
('2','Tran Thi','Binh','binhtt','123','Staff','80'),
('3','Le Thi','Canh','canhlt','123','Staff','30'),
('4','Dang Thi','Duyen','duyentd','123','Writer','20'),
('5','Nguyen Nam','Em','emnn','123','Director','10')
SELECT *FROM PERSON;

SELECT STT,FIRSTNAME,LASTNAME,BIRTHDAY, NICKNAME, ROLE FROM PERSON;